### ISSUE TITLE
PyPi Wheels missing for Windows & Mac

### ISSUE THREAD

**Issue by ghaarsma** [ecmwf/ecmwflibs#14]
### What happened?

For [ecmwflibs 5.1 Wheels](https://pypi.org/project/ecmwflibs/0.5.1/#files) Wheels were provided for Windows and ManyLinux.

For all 4 of the later releases, I can only find [Wheels](https://pypi.org/project/ecmwflibs/#files) for MacOSX

### What are the steps to reproduce the bug?

See [](https://pypi.org/project/ecmwflibs/#files)

![image](https://github.com/ecmwf/ecmwflibs/assets/4742514/da5400e8-3115-47c8-a012-c2cd48118f07)

### Version

After 5.1

### Platform (OS and architecture)

Windows and ManyLinux

**Comment by thebaptiste** [comment]
These wheels are also missing to me for release 0.5.5 (ok for 0.5.3)

![wheels](https://github.com/ecmwf/ecmwflibs/assets/19856429/e29dfb6e-e5ed-4dee-b850-140e32d4ac99)

**Comment by ghaarsma** [comment]
I would like to update the orignal "bug" report about the missing wheels for Windows and Mac on [PyPi](https://pypi.org/project/ecmwflibs/).

While Mac wheels have been added to releases: [0.5.2](https://pypi.org/project/ecmwflibs/0.5.2/#files) till [0.5.6](https://pypi.org/project/ecmwflibs/0.5.6/#files), the Windows wheels are still missing for any release after [5.1.0](https://pypi.org/project/ecmwflibs/0.5.1/#files)

The latest current version [0.5.7](https://pypi.org/project/ecmwflibs/0.5.7/#files) only has linux wheels available.

The [Python Wheels](https://pythonwheels.com/) provides a link to [cibuildwheel](https://github.com/pypa/cibuildwheel) that might be helpfull in building wheels across Mac, Linux, Windows, on multiple versions of Python.

**Comment by ghaarsma** [comment]
Version [0.6.1](https://pypi.org/project/ecmwflibs/#files) now has wheels for ManyLinux, MacOS, & Windows.

Many thanks to fixing this up.
