### ISSUE TITLE
Source distribution is not provided

### ISSUE THREAD

**Issue by thebaptiste** [ecmwf/ecmwflibs#2]
For some reason, we need to install all python packages from source distribution (pip install with option --no-binary)
It doesn't work for ecmwflibs because you only provide wheels.

Is it in your roadmap to also provide source distribution ?

**Comment by thebaptiste** [comment]
If you don't want to change it in your repository, maybe it's something you could change "on the fly" in the GitHub Action used to publish the package. That's what we are doing for some of our packages, see for example the workflow for [mflog](https://github.com/metwork-framework/mflog)

**Comment by b8raoult** [comment]
It is not currently possible to create a source distribution that is compiled on the user's computer, as there are too many external dependencies required. But contributions are welcome. I will close the PR for now.
