### ISSUE TITLE
Not updated version on PyPi

### ISSUE THREAD

**Issue by NTN-code** [ecmwf/ecmwflibs#31]
### What happened?

I try to install lastest version ecmwflibs from PyPi, but it doesn't publish.

### What are the steps to reproduce the bug?

Go to the link: https://pypi.org/project/ecmwflibs/ 

Screenshot from 31/12/2023 =)
![изображение](https://github.com/ecmwf/ecmwflibs/assets/69033707/5080576b-9909-4939-ba95-40abbc59a345)

### Version

0.5.7

### Platform (OS and architecture)

WSL(Ubuntu)

**Comment by niltecedu** [comment]
Same. Any way we can help for this?
