### ISSUE TITLE
Compile eccodes with png support enabled

### ISSUE THREAD

**Issue by andersonad** [ecmwf/ecmwflibs#4]
This library is really nice for not having to support a build chain when using cfgrib and xarray.

One of the weather data sources we often work with is MRMS, which requires PNG support enabled. I understand this is not done by default on ecCodes right now, but would it be possible to add that flag when building the library for the wheel?

**Comment by floriankrb** [comment]
@andersonad, please try with version 0.4.8 which includes PNG support.

**Comment by floriankrb** [comment]
I am assuming that the change we made to add the PNG support is working for you. Feel free to reopen if it doesn't.

**Comment by andersonad** [comment]
My apologies for failing to get back to you in a timely manner. This change is in fact working for me in the latest release. Thank you very much!
