### ISSUE TITLE
Missing linux wheels for release 0.4.16 on pypi

### ISSUE THREAD

**Issue by thebaptiste** [ecmwf/ecmwflibs#6]
Hello
Several wheels are missing on pypi for the last release 0.4.16. The only available for linux is the one for python 3.6. They are missing for python 3.7, 3.8, 3.9... Even if I don't use them, other wheels are missing for MacOS and Windows...
Thanks

**Comment by EduardRosert** [comment]
This issue is now resolved with release 0.4.17. Thanks for reporting!

**Comment by thebaptiste** [comment]
Thanks
